"""Package di integrazione Airtable per Melpis.

Esporta il contratto (AirtablePort), l'adapter di produzione (AirtableAdapter),
i modelli DTO tipizzati, il layer di mapping dinamico e la gerarchia di errori.
"""
from src.integrations.airtable.adapter import AirtableAdapter
from src.integrations.airtable.errors import (
    AirtableAuthError,
    AirtableError,
    AirtableInvalidBaseError,
    AirtableInvalidTableError,
    AirtableMalformedResponseError,
    AirtableMalformedWebhookError,
    AirtableMappingError,
    AirtableMedicalPolicyError,
    AirtableMissingDataError,
    AirtableMissingFieldMappingError,
    AirtableNetworkError,
    AirtableNotFoundError,
    AirtableQuotaExhaustedError,
    AirtableRateLimitError,
    AirtableServerError,
    AirtableUnknownIntegrationError,
    AirtableValidationError,
    AirtableWebhookAuthError,
    AirtableWebhookError,
    AirtableWebhookOwnershipError,
    AirtableWebhookProcessingError,
)
from src.integrations.airtable.mapping_service import AirtableMappingService
from src.integrations.airtable.models import (
    AirtableBase,
    AirtableField,
    AirtableRecord,
    AirtableTable,
    AirtableWebhookEvent,
    AirtableWebhookNotification,
    AirtableWebhookSubscription,
    BatchRecordItem,
    BatchUpdateRecordItem,
    CreateMappingRequest,
    CreateRecordRequest,
    DeleteRecordResult,
    ListRecordsParams,
    PaginationParams,
    RecordPage,
    STANDARD_ENTITY_REQUIRED_FIELDS,
    SchemaValidationResult,
    TableFieldMapping,
    UpdateMappingRequest,
    UpdateRecordRequest,
)
from src.integrations.airtable.port import AirtablePort
from src.integrations.airtable.repository import (
    AirtableConnectionRepository,
    AirtableMappingRepository,
    AirtableWebhookRepository,
)
from src.integrations.airtable.service import AirtableConnectionService
from src.integrations.airtable.webhook_service import (
    AirtableWebhookPayloadFetcher,
    AirtableWebhookService,
)
from src.integrations.airtable.ai_service import AirtableAIService
from src.integrations.airtable.ai_tools import (
    CreateCustomerTool,
    CreateLeadTool,
    CreateRequestTool,
    CreateTicketTool,
    DeleteRecordTool,
    FindCustomerTool,
    SearchRecordsTool,
    UpdateCustomerTool,
    create_airtable_tools,
)
from src.integrations.airtable.errors import (
    AirtableAIError,
    AirtableConfirmationRequiredError,
    AirtableSchemaModificationProhibitedError,
)

__all__ = [
    "AirtablePort",
    "AirtableAdapter",
    "AirtableBase",
    "AirtableTable",
    "AirtableField",
    "AirtableRecord",
    "BatchRecordItem",
    "BatchUpdateRecordItem",
    "CreateRecordRequest",
    "UpdateRecordRequest",
    "DeleteRecordResult",
    "ListRecordsParams",
    "PaginationParams",
    "RecordPage",
    "SchemaValidationResult",
    "TableFieldMapping",
    "CreateMappingRequest",
    "UpdateMappingRequest",
    "STANDARD_ENTITY_REQUIRED_FIELDS",
    "AirtableWebhookSubscription",
    "AirtableWebhookNotification",
    "AirtableWebhookEvent",
    "AirtableConnectionRepository",
    "AirtableMappingRepository",
    "AirtableWebhookRepository",
    "AirtableConnectionService",
    "AirtableMappingService",
    "AirtableWebhookService",
    "AirtableWebhookPayloadFetcher",
    "AirtableAIService",
    "create_airtable_tools",
    "FindCustomerTool",
    "CreateCustomerTool",
    "UpdateCustomerTool",
    "CreateLeadTool",
    "CreateRequestTool",
    "CreateTicketTool",
    "SearchRecordsTool",
    "DeleteRecordTool",
    "AirtableAIError",
    "AirtableConfirmationRequiredError",
    "AirtableSchemaModificationProhibitedError",
    "AirtableError",
    "AirtableMedicalPolicyError",
    "AirtableAuthError",
    "AirtableNotFoundError",
    "AirtableValidationError",
    "AirtableRateLimitError",
    "AirtableQuotaExhaustedError",
    "AirtableServerError",
    "AirtableNetworkError",
    "AirtableMalformedResponseError",
    "AirtableMappingError",
    "AirtableMissingFieldMappingError",
    "AirtableInvalidTableError",
    "AirtableInvalidBaseError",
    "AirtableMissingDataError",
    "AirtableWebhookError",
    "AirtableWebhookAuthError",
    "AirtableWebhookOwnershipError",
    "AirtableUnknownIntegrationError",
    "AirtableMalformedWebhookError",
    "AirtableWebhookProcessingError",
]
